### ISSUE TITLE
serverless-package-external deleted my project folder

### ISSUE THREAD

**Issue by deathemperor** [epsagon/serverless-package-external#16]
Running `serverless package` with this plugin. it deletes my project folders with unpushed source codes...

This is the only error I got. I don't have any source code to show what config I set LOL.
```
Serverless: [serverless-package-external] Symlinking utils/**
Serverless: [serverless-package-external] Symlinking keys/**
Serverless: [serverless-package-external] Symlinking gql/**

  Error --------------------------------------------------

  Error: ENOENT: no such file or directory, symlink 'utils/**' -> '/Users/x/xx/xxx-lambda/**'
      at Object.symlinkSync (fs.js:1005:3)
      at /Users/x/xx/xx-lambda/node_modules/serverless-package-external/src/symlink.js:45:10
      at async Promise.all (index 0)
```

**Comment by deathemperor** [comment]
LUCKILY, VS code still has all my opened files in memory that I can recover by copying them out.

This is the config I used:

```
custom:
  webpack:
    includeModules:
      forceInclude:
        - chrome-aws-lambda
  packageExternal:
    external:
      - utils/**
      - keys/**
      - gql/**
```

**Comment by vitorpiovezam** [comment]
Same here, the project folder is deleted forever, critical bug.

**Comment by tanalam2411** [comment]
Yes, happened for me too and I was not lucky.

**Comment by ranrib** [comment]
Hi @tanalam2411 @deathemperor @vitorpiovezam - I can't manage to repro this, using the following yml:
```
service:
  name: test-sls


custom:
  external:
      - utils/**
      - keys/**
      - gql/**
  
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev

functions:
  first-func:
    handler: handler.first

plugins:
  - serverless-package-external
```

Can you kindly share something minimal that reproduces this error?

**Comment by ernesto** [comment]
Same here, the lib erase all directory. For me, i am using with serverless-python-requirements plugin and individuals modules

**Comment by ranrib** [comment]
> Same here, the lib erase all directory. For me, i am using with serverless-python-requirements plugin and individuals modules

Hi @ernesto , can you please share a reproducible project? I can't seem to recreate this issue

**Comment by TimoLatruwe** [comment]
Same issue, deleted the entire folder. 

```
Serverless: [serverless-package-external] Symlinking ../common/*
Serverless: [serverless-package-external] is complete
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
```

**Comment by ranrib** [comment]
Hi @TimoLatruwe , can you somehow share a reproducible zip? I couldn't reproduce it..

**Comment by adminy** [comment]
Why did this get closed if it didn't get fixed?
```yml
service:
  name: test-sls


custom:
  packageExternal:
    external:
      - './common'
      - './functions'
  
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: dev

functions:
  first-func:
    handler: handler.first
    module: functions/function-a

plugins:
  - serverless-package-external
```

**Comment by ranrib** [comment]
> Why did this get closed if it didn't get fixed?
> 
> ```yaml
> service:
>   name: test-sls
> 
> 
> custom:
>   packageExternal:
>     external:
>       - './common'
>       - './functions'
>   
> provider:
>   name: aws
>   runtime: python3.7
>   region: eu-west-1
>   stage: dev
> 
> functions:
>   first-func:
>     handler: handler.first
>     module: functions/function-a
> 
> plugins:
>   - serverless-package-external
> ```

@adminy we could not reproduce it, that's why we closed it. This example still doesn't reproduce the issue. 
Also why are you packaging "external" directories that are located in the same folder `.`?

If you have a working replication - please feel free to suggest a fix. Thanks,

**Comment by adminy** [comment]
The reason I'm doing that is because some lambdas want to be aware of the code of the other lambdas.
I don't know how you cannot reproduce this as I'm getting the error consistently on different machines.

**Comment by ranrib** [comment]
Maybe it's not just the example yml, but some other configuration. Will you be willing to open a PR with a fix and solve this problem for everyone? 💯

**Comment by adminy** [comment]
Sure, I'll give it a try later today.

**Comment by bram-tv** [comment]
> I can't manage to repro this, using the following yml:
> 
> ```
> service:
>   name: test-sls
> 
> 
> custom:
>   external:
>       - utils/**
>       - keys/**
>       - gql/**
>   
> provider:
>   name: aws
>   runtime: python3.6
>   region: eu-west-1
>   stage: dev
> 
> functions:
>   first-func:
>     handler: handler.first
> 
> plugins:
>   - serverless-package-external
> ```
> 
> Can you kindly share something minimal that reproduces this error?

The key to reproducing this is to use a pattern such as `utils/**` which you did in the above example but what is missing in the above example is that you're not configuring your plugin.

That is:
```
custom:
  external:
      - utils/**
      - keys/**
      - gql/**
```
should be:
```
custom:
  packageExternal:
    external:
      - utils/**
      - keys/**
      - gql/**
```

Anyway, a full example:
```
~$ find issue_16/ -type f | wc -l
13879
~$ cd issue_16/
~/issue16$ cat serverless.yml
service: test-sls

custom:
  packageExternal:
    external:
      - utils/**
      - keys/**
      - gql/**

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev

functions:
  first-func:
    handler: handler.first

plugins:
  - serverless-package-external

~/issue_16$ yarn serverless package --verbose --debug true
yarn run v1.22.19
warning package.json: No license field
$ /home/test-serverless/issue_16/node_modules/.bin/serverless package --verbose --debug true

Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, ruby2.7, ruby3.2]

Learn more about configuration validation here: http://slss.io/configuration-validation

Packaging test-sls for stage dev (eu-west-1)

Packaging
[serverless-package-external] Symlinking utils/**
[serverless-package-external] Symlinking keys/**
[serverless-package-external] Symlinking gql/**
Environment: linux, node 16.17.0, framework 3.32.2 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: ENOENT: no such file or directory, symlink 'utils/**' -> '/home/test-serverless/issue_16/**'
    at Object.symlinkSync (node:fs:1705:3)
    at /home/test-serverless/issue_16/node_modules/serverless-package-external/src/symlink.js:46:12
    at async Promise.all (index 0)
    at async PluginManager.runHooks (/home/test-serverless/issue_16/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/home/test-serverless/issue_16/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/home/test-serverless/issue_16/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/home/test-serverless/issue_16/node_modules/serverless/lib/serverless.js:179:5)
    at async /home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js:834:9

1 deprecation found: run 'serverless doctor' for more details
✖ Uncaught exception
/home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js:54
        throw error;
        ^

Error: Cannot find module '../../../package'
Require stack:
- /home/test-serverless/issue_16/node_modules/serverless/lib/utils/telemetry/generate-payload.js
- /home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js
- /home/test-serverless/issue_16/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/test-serverless/issue_16/node_modules/serverless/lib/utils/telemetry/generate-payload.js:189:21
    at module.exports (/home/test-serverless/issue_16/node_modules/serverless/lib/utils/telemetry/generate-payload.js:192:5)
    at finalize (/home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js:75:8)
    at async /home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js:866:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/test-serverless/issue_16/node_modules/serverless/lib/utils/telemetry/generate-payload.js',
    '/home/test-serverless/issue_16/node_modules/serverless/scripts/serverless.js',
    '/home/test-serverless/issue_16/node_modules/serverless/bin/serverless.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/issue_16$ cd ..
~$ find issue_16/ -type f | wc -l
find: 'issue_16/': No such file or directory
0
```

**Note**: I don't expect such a pattern to work (nor do I really care if it works) but at least you should be able to reproduce it now.
